#!/usr/bin/env bash

# stop if we encounter an error
set -e

# check args
if [ $# -ne 1 ]; then
    echo "usage: $0 <build-workspace>"
    exit 1
fi

# setup variables
BUILD_WORKSPACE="$1"
PROJECT_NAME=PixateFreestyleshowcase
FREESTYLE_WORKSPACE="${BUILD_WORKSPACE}/Freestyle"
PROJECT_WORKSPACE="${FREESTYLE_WORKSPACE}/${PROJECT_NAME}"
PROJECT_BUNDLE="${PROJECT_WORKSPACE}/${PROJECT_NAME}.xcodeproj"

# build Freestyle
mkdir -p "${FREESTYLE_WORKSPACE}"
cp -r ./ "${FREESTYLE_WORKSPACE}"

# remove unneeded project-related files
rm -rf "${PROJECT_BUNDLE}/xcshareddata"
rm -rf "${PROJECT_BUNDLE}/xcuserdata"
rm -rf "${PROJECT_BUNDLE}/project.xcworkspace"

# re-map location of Pixate
perl -p -i -e 's|path = Pixate.framework;|name = Pixate.framework; path = ../../Framework/Pixate.framework;|g' "${PROJECT_BUNDLE}/project.pbxproj"

# remove build files
rm -rf "${FREESTYLE_WORKSPACE}/.git"
rm -f "${FREESTYLE_WORKSPACE}/.gitignore"
rm -f "${FREESTYLE_WORKSPACE}/build-all"

rm -rf "${PROJECT_WORKSPACE}/Pixate.framework"
rm -rf "${PROJECT_WORKSPACE}/${PROJECT_NAME}Tests"
